name: Auto Increment Version

on:
  push:
    branches:
      - main

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Checkout version branch
        run: |
          git fetch origin version
          git checkout version

      - name: List files in version branch
        run: |
          ls -la

      - name: Check if version file exists
        run: |
          if [ ! -f version.txt ]; then
            echo "Version file does not exist!"
            exit 1
          fi

      - name: Read current version
        id: get_version
        run: |
          version=$(cat version.txt)
          echo "::set-output name=version::$version"

      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -r major minor <<< "${{ steps.get_version.outputs.version }}"
          minor=$((minor + 1))
          new_version="$major.$minor"
          echo "$new_version" > version.txt
          echo "::set-output name=new_version::$new_version"

      - name: Commit and push changes to version branch
        run: |
          git add version.txt
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin version
